---
# Install Docker on Ubuntu Bionic

- name: ensure old versions of docker are uninstalled
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
- name: update required packages to latest version
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
- name: add docker public gpg key to apt keyring
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
- name: add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
